# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Admin/Desktop/7020/lcd/vivado/lcd/lcd.srcs/sources_1/bd/lcd/ip/lcd_processing_system7_0_0/lcd_processing_system7_0_0.xci
# IP: The module: 'lcd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/7020/lcd/vivado/lcd/lcd.gen/sources_1/bd/lcd/ip/lcd_processing_system7_0_0/lcd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Admin/Desktop/7020/lcd/vivado/lcd/lcd.srcs/sources_1/bd/lcd/ip/lcd_processing_system7_0_0/lcd_processing_system7_0_0.xci
# IP: The module: 'lcd_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Admin/Desktop/7020/lcd/vivado/lcd/lcd.gen/sources_1/bd/lcd/ip/lcd_processing_system7_0_0/lcd_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lcd_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
