# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/LCD.xdc

# Block Designs: bd/lcd/lcd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd || ORIG_REF_NAME==lcd} -quiet] -quiet

# IP: bd/lcd/ip/lcd_processing_system7_0_0/lcd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lcd_processing_system7_0_0 || ORIG_REF_NAME==lcd_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/Admin/Desktop/7020/lcd/vivado/lcd/lcd.gen/sources_1/bd/lcd/lcd_ooc.xdc
